site_name: Build your own Newsletter using Step Functions
theme:
  name: material
  palette:
    primary: orange
    scheme: preference

markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - Step 1 - Getting started: step1.md
  - Step 2 - Fetch Data from DynamoDB: step2.md
  - Step 3 - Intro to Direct Integrations: step3.md
  - Understanding Input & Output Processing: io.md
  - Step 4 - Intro to Map State: step4.md
  - Step 5 - Callback Pattern: step5.md
  - Scheduling Your Step Function: schedule.md
  - Sample Input: sample-input.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/SrushithR
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SrushithR
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/srushith/